main: io.github.thatsmusic99.specprotect.CoreClass
name: SpectateProtection
version: 1.1.3
author: Thatsmusic99
api-version: 1.13
commands:
  sp:
    description: Main SpectateProtection command.
    permission: sp.maincommand
    usage: /<command>
    aliases: [specprotect, spectateprotection]